"""
Generate all Jupyter notebooks (02-11) for Milestones 9-18.
Run from project root: python3 scripts/generate_notebooks.py
"""

import json
import os

os.makedirs('notebooks', exist_ok=True)

def make_nb(cells):
    return {
        'nbformat': 4, 'nbformat_minor': 5,
        'metadata': {
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python', 'version': '3.9.6'}
        },
        'cells': cells
    }

def md(lines):
    if isinstance(lines, str): lines = [lines]
    return {'cell_type': 'markdown', 'metadata': {}, 'source': lines}

def code(lines):
    if isinstance(lines, str): lines = [lines]
    return {'cell_type': 'code', 'metadata': {}, 'source': lines, 'outputs': [], 'execution_count': None}

def save(nb, path):
    with open(path, 'w') as f:
        json.dump(nb, f, indent=1)
    print(f'  Created {path}')

# ==================== 02_eda.ipynb ====================
save(make_nb([
    md(['# 02 — Exploratory Data Analysis\n',
        'Distributions, class imbalance, correlations, and outlier detection.']),
    code(['import pandas as pd\n', 'import matplotlib.pyplot as plt\n', 'import seaborn as sns\n', 'import os\n',
          '\n', 'from src.config import DATA_PROCESSED_PATH, NUMERICAL_FEATURES, CATEGORICAL_FEATURES, TARGET\n',
          '\n', "sns.set_style('whitegrid')\n", "plt.rcParams['figure.figsize'] = (12, 8)\n",
          "os.makedirs('docs/eda_plots', exist_ok=True)\n", '\n',
          'df = pd.read_csv(DATA_PROCESSED_PATH)\n', 'print(f"Loaded {df.shape[0]:,} rows")']),
    md('## 1. Numerical Feature Distributions'),
    code(['fig, axes = plt.subplots(3, 3, figsize=(20, 15))\n', 'axes = axes.flatten()\n', '\n',
          'for i, col in enumerate(NUMERICAL_FEATURES):\n',
          "    df[col].hist(bins=50, ax=axes[i], edgecolor='black', alpha=0.7)\n",
          "    axes[i].set_title(col, fontsize=14, fontweight='bold')\n",
          "    axes[i].set_ylabel('Count')\n", '\n', 'plt.tight_layout()\n',
          "plt.savefig('docs/eda_plots/hist_numerical.png', dpi=150, bbox_inches='tight')\n", 'plt.show()']),
    md(['**Interpretation:**\n',
        '- `Income` and `LoanAmount` span wide ranges with roughly uniform distribution\n',
        '- `CreditScore` ranges 300–850 with even spread\n',
        '- `DTIRatio` is uniformly distributed between 0.0 and 1.0\n',
        '- `NumCreditLines` has only values 1–4 (discrete)']),
    md('## 2. Class Imbalance Visualization'),
    code(['fig, ax = plt.subplots(figsize=(8, 6))\n',
          'counts = df[TARGET].value_counts()\n', 'total = len(df)\n',
          "bars = ax.bar(['No Default (0)', 'Default (1)'], counts.values,\n",
          "              color=['#2ecc71', '#e74c3c'], edgecolor='black')\n",
          'for bar, count in zip(bars, counts.values):\n',
          '    pct = count / total * 100\n',
          "    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 500,\n",
          "            f'{count:,}\\n({pct:.1f}%)', ha='center', fontsize=14)\n",
          "ax.set_title('Class Distribution — Default', fontsize=16, fontweight='bold')\n",
          "ax.set_ylabel('Count')\n",
          "plt.savefig('docs/eda_plots/class_imbalance.png', dpi=150, bbox_inches='tight')\n", 'plt.show()']),
    md('## 3. Boxplots — Income and LoanAmount by Default Status'),
    code(['fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n',
          "for i, col in enumerate(['Income', 'LoanAmount']):\n",
          "    sns.boxplot(data=df, x=TARGET, y=col, ax=axes[i], palette=['#2ecc71', '#e74c3c'])\n",
          "    axes[i].set_title(f'{col} by Default Status', fontsize=14, fontweight='bold')\n",
          "    axes[i].set_xticklabels(['No Default', 'Default'])\n",
          'plt.tight_layout()\n',
          "plt.savefig('docs/eda_plots/boxplot_income.png', dpi=150, bbox_inches='tight')\n", 'plt.show()']),
    md('## 4. Correlation Heatmap'),
    code(['fig, ax = plt.subplots(figsize=(12, 10))\n',
          'corr = df[NUMERICAL_FEATURES + [TARGET]].corr()\n',
          "sns.heatmap(corr, annot=True, cmap='RdBu_r', center=0, fmt='.2f', square=True, ax=ax)\n",
          "ax.set_title('Correlation Heatmap', fontsize=16, fontweight='bold')\n",
          "plt.savefig('docs/eda_plots/correlation_heatmap.png', dpi=150, bbox_inches='tight')\n", 'plt.show()']),
    md('## 5. Categorical Feature Distributions'),
    code(['fig, axes = plt.subplots(1, 3, figsize=(20, 6))\n',
          "for i, col in enumerate(['Education', 'LoanPurpose', 'EmploymentType']):\n",
          "    df[col].value_counts().plot(kind='barh', ax=axes[i], color='#3498db', edgecolor='black')\n",
          "    axes[i].set_title(f'{col} — Value Counts', fontsize=14, fontweight='bold')\n",
          '    axes[i].invert_yaxis()\n', 'plt.tight_layout()\n',
          "plt.savefig('docs/eda_plots/categorical_distributions.png', dpi=150, bbox_inches='tight')\n", 'plt.show()']),
    md(['## 6. Key EDA Findings\n',
        '1. **Class Imbalance:** ~88% No Default vs ~12% Default — 7.6:1 ratio\n',
        '2. **No Missing Values:** Dataset is clean, but we keep imputers in pipeline for safety\n',
        '3. **Feature Ranges:** Income (15K–150K), LoanAmount (5K–250K), CreditScore (300–850)\n',
        '4. **Low Correlation to Target:** No single feature strongly predicts default\n',
        '5. **Categorical Balance:** Education and EmploymentType categories are roughly balanced'])
]), 'notebooks/02_eda.ipynb')

# ==================== 03_train_test_split.ipynb ====================
save(make_nb([
    md(['# 03 — Train-Test Split\n', 'Stratified 80/20 split preserving class distribution.']),
    code(['import pandas as pd\n', 'from sklearn.model_selection import train_test_split\n',
          'from src.config import (\n', '    DATA_PROCESSED_PATH, NUMERICAL_FEATURES,\n',
          '    CATEGORICAL_FEATURES, TARGET, RANDOM_STATE, TEST_SIZE\n', ')']),
    md('## 1. Load Clean Data and Separate Features/Target'),
    code(['df = pd.read_csv(DATA_PROCESSED_PATH)\n',
          'X = df[NUMERICAL_FEATURES + CATEGORICAL_FEATURES]\n', 'y = df[TARGET]\n',
          'print(f"X shape: {X.shape}, y shape: {y.shape}")\n',
          'print(f"Default rate: {y.mean()*100:.1f}%")']),
    md(['## 2. Stratified Split\n',
        '`stratify=y` ensures both train and test sets have the same ~88/12 class ratio.\n',
        'Without this, random chance could give the test set a different ratio,\n',
        'making evaluation unreliable.']),
    code(['X_train, X_test, y_train, y_test = train_test_split(\n',
          '    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y\n', ')\n', '\n',
          'print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")\n',
          'print(f"y_train: {y_train.shape}, y_test: {y_test.shape}")\n',
          'print(f"\\nTrain class distribution:\\n{y_train.value_counts(normalize=True).round(4)}")\n',
          'print(f"\\nTest class distribution:\\n{y_test.value_counts(normalize=True).round(4)}")']),
    md('## 3. Verify Stratification'),
    code(['assert abs(y_train.mean() - y_test.mean()) < 0.01, "Stratification failed!"\n',
          'print(f"Train default rate: {y_train.mean()*100:.2f}%")\n',
          'print(f"Test default rate:  {y_test.mean()*100:.2f}%")\n',
          'print("✓ Stratification verified — both sets have same class ratio")']),
    md('## 4. Save Split Data'),
    code(['import os\n', "os.makedirs('data/processed', exist_ok=True)\n", '\n',
          "X_train.to_csv('data/processed/X_train.csv', index=False)\n",
          "X_test.to_csv('data/processed/X_test.csv', index=False)\n",
          "y_train.to_csv('data/processed/y_train.csv', index=False)\n",
          "y_test.to_csv('data/processed/y_test.csv', index=False)\n", '\n',
          'print("Saved X_train, X_test, y_train, y_test to data/processed/")\n',
          'print(f"Train: {X_train.shape[0]:,} rows | Test: {X_test.shape[0]:,} rows")']),
]), 'notebooks/03_train_test_split.ipynb')

# ==================== 04_preprocessing_pipeline.ipynb ====================
save(make_nb([
    md(['# 04 — Preprocessing Pipeline\n',
        'Build a ColumnTransformer, demonstrate data leakage prevention, compare scalers.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.pipeline import Pipeline\n', 'from sklearn.linear_model import LogisticRegression\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import NUMERICAL_FEATURES, CATEGORICAL_FEATURES, RANDOM_STATE']),
    md('## 1. Load Split Data'),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()\n",
          'print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")']),
    md('## 2. Build and Inspect Preprocessor'),
    code(['preprocessor = build_preprocessor()\n', 'print(preprocessor)']),
    md(['## 3. Data Leakage Demonstration\n',
        'Leakage occurs when test data influences training. Here we show the difference\n',
        'between fitting a scaler on ALL data vs train-only.']),
    code(['from sklearn.preprocessing import StandardScaler\n', '\n',
          '# WRONG: fit on ALL data (leaks test distribution into training)\n',
          'scaler_leak = StandardScaler()\n', "all_income = pd.concat([X_train['Income'], X_test['Income']])\n",
          'scaler_leak.fit(all_income.values.reshape(-1, 1))\n',
          'leaked_mean = scaler_leak.mean_[0]\n', '\n',
          '# CORRECT: fit on train only\n', 'scaler_correct = StandardScaler()\n',
          "scaler_correct.fit(X_train['Income'].values.reshape(-1, 1))\n",
          'correct_mean = scaler_correct.mean_[0]\n', '\n',
          'print(f"Leaked scaler mean (fit on all):    {leaked_mean:,.2f}")\n',
          'print(f"Correct scaler mean (fit on train): {correct_mean:,.2f}")\n',
          'print(f"Difference: {abs(leaked_mean - correct_mean):,.2f}")\n',
          'print("\\n→ In sklearn Pipeline, the preprocessor is fit ONLY on train data inside .fit()")']),
    md('## 4. Full Pipeline with LogisticRegression'),
    code(['pipeline = Pipeline(steps=[\n', "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))\n", '])\n', '\n',
          'pipeline.fit(X_train, y_train)\n', 'print(f"Pipeline score on test: {pipeline.score(X_test, y_test):.4f}")\n',
          'print("\\n✓ Preprocessor fitted ONLY on training data inside the pipeline")']),
    md(['## 5. Key Takeaway\n',
        'The pipeline ensures:\n',
        '1. Preprocessor is fit on train data ONLY\n',
        '2. Same transformations are applied to both train and test\n',
        '3. The entire pipeline can be pickled as one object\n',
        '4. No data leakage is possible']),
]), 'notebooks/04_preprocessing_pipeline.ipynb')

# ==================== 05_baseline.ipynb ====================
save(make_nb([
    md(['# 05 — Baseline Model\n', 'DummyClassifier establishes the floor for all metrics.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.dummy import DummyClassifier\n',
          'from sklearn.metrics import classification_report, f1_score, ConfusionMatrixDisplay\n',
          'import matplotlib.pyplot as plt\n',
          'from src.config import RANDOM_STATE']),
    md('## 1. Load Data'),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md(['## 2. Baseline: Predict Most Frequent Class\n',
        'This always predicts "No Default" (0) — the majority class.']),
    code(["baseline = DummyClassifier(strategy='most_frequent', random_state=RANDOM_STATE)\n",
          'baseline.fit(X_train, y_train)\n', 'y_pred = baseline.predict(X_test)\n', '\n',
          "print(classification_report(y_test, y_pred, target_names=['No Default', 'Default']))"]),
    md(['## 3. Why Accuracy is Misleading\n',
        'The baseline achieves ~88% accuracy by predicting "No Default" for everyone.\n',
        'But it catches **zero** defaulters — F1 on class 1 is 0.00.\n',
        'This is why we use **F1 on class 1** as our primary metric.']),
    code(["f1_baseline = f1_score(y_test, y_pred, pos_label=1)\n",
          'accuracy_baseline = baseline.score(X_test, y_test)\n',
          'print(f"Accuracy: {accuracy_baseline:.4f} (looks good, but misleading)")\n',
          'print(f"F1 (class 1): {f1_baseline:.4f} (reveals the model is useless)")']),
    md('## 4. Confusion Matrix'),
    code(["fig, ax = plt.subplots(figsize=(6, 5))\n",
          "ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=['No Default', 'Default'], ax=ax, cmap='Blues')\n",
          "ax.set_title('Baseline — Confusion Matrix', fontsize=14, fontweight='bold')\n",
          "plt.savefig('docs/eda_plots/baseline_confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
          'plt.show()']),
    md(['## 5. Baseline Scores (saved for comparison)\n',
        '| Metric | Value |\n', '|--------|-------|\n',
        '| Accuracy | ~0.884 |\n', '| F1 (class 1) | 0.000 |\n',
        '| Precision (class 1) | 0.000 |\n', '| Recall (class 1) | 0.000 |']),
]), 'notebooks/05_baseline.ipynb')

# ==================== 06_logistic_regression.ipynb ====================
save(make_nb([
    md(['# 06 — Logistic Regression\n', 'First real model — with full evaluation on classification metrics.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.linear_model import LogisticRegression\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.metrics import classification_report, f1_score, ConfusionMatrixDisplay\n',
          'import matplotlib.pyplot as plt\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import RANDOM_STATE']),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md('## 1. Train Logistic Regression Pipeline'),
    code(['lr_pipeline = Pipeline(steps=[\n', "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))\n", '])\n',
          'lr_pipeline.fit(X_train, y_train)\n',
          'y_pred = lr_pipeline.predict(X_test)\n', '\n',
          "print(classification_report(y_test, y_pred, target_names=['No Default', 'Default']))"]),
    md('## 2. Key Metrics'),
    code(["f1 = f1_score(y_test, y_pred, pos_label=1)\n",
          'accuracy = lr_pipeline.score(X_test, y_test)\n',
          'print(f"Accuracy: {accuracy:.4f}")\n',
          'print(f"F1 (class 1 — our primary metric): {f1:.4f}")\n',
          'print(f"\\nCompare vs Baseline: F1 went from 0.000 → {f1:.4f}")']),
    md('## 3. Confusion Matrix'),
    code(["fig, ax = plt.subplots(figsize=(6, 5))\n",
          "ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=['No Default', 'Default'], ax=ax, cmap='Blues')\n",
          "ax.set_title('Logistic Regression — Confusion Matrix', fontsize=14, fontweight='bold')\n",
          "plt.savefig('docs/eda_plots/lr_confusion_matrix.png', dpi=150, bbox_inches='tight')\n",
          'plt.show()']),
    md(['## 4. Interpretation\n',
        '- **False Negatives (FN):** Borrowers who defaulted but model predicted safe → financial loss\n',
        '- **False Positives (FP):** Safe borrowers flagged as risky → lost business opportunity\n',
        '- For lending, FN is more costly than FP\n',
        '- Next: try class_weight and SMOTE to improve recall on defaulters']),
]), 'notebooks/06_logistic_regression.ipynb')

# ==================== 07_imbalance.ipynb ====================
save(make_nb([
    md(['# 07 — Handling Class Imbalance\n',
        '3-way comparison: Plain LR vs class_weight="balanced" vs SMOTE.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.linear_model import LogisticRegression\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.metrics import classification_report, f1_score\n',
          'from imblearn.over_sampling import SMOTE\n',
          'from imblearn.pipeline import Pipeline as ImbPipeline\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import RANDOM_STATE']),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md(['## 1. Why Imbalance Matters\n',
        '- Dataset: 88% No Default, 12% Default\n',
        '- A model predicting all-0 gets 88% accuracy but catches zero defaulters\n',
        '- We need to help the model pay more attention to the minority class']),
    md('## 2. Method A: class_weight="balanced"'),
    code(["lr_weighted = Pipeline(steps=[\n", "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE, class_weight='balanced'))\n",
          '])\n', 'lr_weighted.fit(X_train, y_train)\n',
          'y_pred_w = lr_weighted.predict(X_test)\n',
          "print(classification_report(y_test, y_pred_w, target_names=['No Default', 'Default']))"]),
    md(['## 3. Method B: SMOTE\n',
        '**Critical:** SMOTE must ONLY be applied on training data.\n',
        'We use `imblearn.pipeline.Pipeline` (NOT sklearn.pipeline.Pipeline)\n',
        'because sklearn Pipeline does NOT apply sampling steps correctly.']),
    code(['smote_pipeline = ImbPipeline(steps=[\n', "    ('preprocessor', build_preprocessor()),\n",
          "    ('smote', SMOTE(random_state=RANDOM_STATE)),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))\n", '])\n',
          'smote_pipeline.fit(X_train, y_train)\n',
          'y_pred_s = smote_pipeline.predict(X_test)\n',
          "print(classification_report(y_test, y_pred_s, target_names=['No Default', 'Default']))"]),
    md('## 4. Verify Test Set Was NOT Resampled'),
    code(['print(f"X_test shape: {X_test.shape} — unchanged after SMOTE pipeline")\n',
          'print(f"y_test distribution: {np.bincount(y_test)}")\n',
          'print("✓ Test set was NOT resampled — SMOTE only affected training")']),
    md('## 5. Three-Way Comparison'),
    code(['# Plain LR\n', 'lr_plain = Pipeline(steps=[\n', "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))\n", '])\n',
          'lr_plain.fit(X_train, y_train)\n', 'y_pred_p = lr_plain.predict(X_test)\n', '\n',
          'results = pd.DataFrame({\n', "    'Model': ['Plain LR', 'LR + class_weight', 'LR + SMOTE'],\n",
          "    'F1 (class 1)': [\n",
          '        f1_score(y_test, y_pred_p, pos_label=1),\n',
          '        f1_score(y_test, y_pred_w, pos_label=1),\n',
          '        f1_score(y_test, y_pred_s, pos_label=1),\n', '    ]\n', '})\n',
          'print(results.to_string(index=False))']),
]), 'notebooks/07_imbalance.ipynb')

# ==================== 08_knn_and_tree.ipynb ====================
save(make_nb([
    md(['# 08 — KNN + Decision Tree\n',
        'Two non-linear models with bias-variance analysis and feature importance.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.neighbors import KNeighborsClassifier\n',
          'from sklearn.tree import DecisionTreeClassifier\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.preprocessing import MinMaxScaler\n',
          'from sklearn.compose import ColumnTransformer\n',
          'from sklearn.impute import SimpleImputer\n',
          'from sklearn.preprocessing import OneHotEncoder\n',
          'from sklearn.model_selection import GridSearchCV\n',
          'from sklearn.metrics import classification_report, f1_score\n',
          'import matplotlib.pyplot as plt\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import NUMERICAL_FEATURES, CATEGORICAL_FEATURES, RANDOM_STATE']),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md(['## 1. KNN — with Sampling\n',
        'KNN is O(n*d) at prediction time. We sample 30K training rows for speed.']),
    code([
        'SAMPLE_SIZE = 30000\n', 'np.random.seed(RANDOM_STATE)\n',
        '# CORRECT: integer indexing — works with numpy y_train\n',
        'sample_idx = np.random.choice(len(X_train), size=min(SAMPLE_SIZE, len(X_train)), replace=False)\n',
        'X_train_knn = X_train.iloc[sample_idx]\n',
        'y_train_knn = y_train[sample_idx]  # numpy array — integer index works\n', '\n',
        'print(f"KNN training set: {X_train_knn.shape} (sampled from {X_train.shape[0]:,})")\n',
        'print(f"Class dist in sample: {np.bincount(y_train_knn)}")']),
    md('### KNN with MinMaxScaler (better for distance-based models)'),
    code(['# Build MinMaxScaler preprocessor for KNN\n',
          'knn_num_pipeline = Pipeline(steps=[\n',
          "    ('imputer', SimpleImputer(strategy='median')),\n",
          "    ('scaler', MinMaxScaler())\n", '])\n',
          'knn_cat_pipeline = Pipeline(steps=[\n',
          "    ('imputer', SimpleImputer(strategy='most_frequent')),\n",
          "    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))\n", '])\n',
          'knn_preprocessor = ColumnTransformer(transformers=[\n',
          "    ('num', knn_num_pipeline, NUMERICAL_FEATURES),\n",
          "    ('cat', knn_cat_pipeline, CATEGORICAL_FEATURES)\n", '])\n', '\n',
          '# GridSearchCV over k values\n',
          'knn_pipeline = Pipeline(steps=[\n',
          "    ('preprocessor', knn_preprocessor),\n",
          "    ('classifier', KNeighborsClassifier())\n", '])\n', '\n',
          "param_grid = {'classifier__n_neighbors': [3, 5, 7, 11, 15]}\n",
          "grid_knn = GridSearchCV(knn_pipeline, param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)\n",
          'grid_knn.fit(X_train_knn, y_train_knn)\n', '\n',
          'print(f"Best k: {grid_knn.best_params_}")\n',
          'print(f"Best CV F1: {grid_knn.best_score_:.4f}")\n', '\n',
          'y_pred_knn = grid_knn.predict(X_test)\n',
          'print(f"\\nTest F1 (class 1): {f1_score(y_test, y_pred_knn, pos_label=1):.4f}")\n',
          "print(classification_report(y_test, y_pred_knn, target_names=['No Default', 'Default']))"]),
    md('## 2. Decision Tree — Bias-Variance Analysis'),
    code(['# Train trees with different max_depth values\n',
          'depths = [3, 5, 7, 10, None]\n', 'train_f1s = []\n', 'test_f1s = []\n', '\n',
          'for depth in depths:\n',
          '    dt = Pipeline(steps=[\n', "        ('preprocessor', build_preprocessor()),\n",
          "        ('classifier', DecisionTreeClassifier(max_depth=depth, random_state=RANDOM_STATE))\n",
          '    ])\n', '    dt.fit(X_train, y_train)\n',
          '    train_f1s.append(f1_score(y_train, dt.predict(X_train), pos_label=1))\n',
          '    test_f1s.append(f1_score(y_test, dt.predict(X_test), pos_label=1))\n',
          "    print(f'depth={str(depth):>4s} | train F1={train_f1s[-1]:.4f} | test F1={test_f1s[-1]:.4f}')"]),
    md('### Bias-Variance Visualization'),
    code(["depth_labels = [str(d) if d else 'None' for d in depths]\n",
          'fig, ax = plt.subplots(figsize=(10, 6))\n',
          "ax.plot(depth_labels, train_f1s, 'o-', label='Train F1', linewidth=2)\n",
          "ax.plot(depth_labels, test_f1s, 's-', label='Test F1', linewidth=2)\n",
          "ax.set_xlabel('max_depth')\n", "ax.set_ylabel('F1 Score (class 1)')\n",
          "ax.set_title('Decision Tree: Bias vs Variance', fontsize=14, fontweight='bold')\n",
          'ax.legend()\n', "ax.grid(True, alpha=0.3)\n",
          "plt.savefig('docs/eda_plots/bias_variance_dt.png', dpi=150, bbox_inches='tight')\n",
          'plt.show()']),
    md('## 3. Feature Importance (from best Decision Tree)'),
    code(['best_depth = depths[np.argmax(test_f1s)]\n',
          'dt_best = Pipeline(steps=[\n', "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', DecisionTreeClassifier(max_depth=best_depth, random_state=RANDOM_STATE))\n",
          '])\n', 'dt_best.fit(X_train, y_train)\n', '\n',
          '# Get feature names after encoding\n',
          "feature_names = (NUMERICAL_FEATURES + \n",
          "    list(dt_best.named_steps['preprocessor']\n",
          "         .named_transformers_['cat']\n",
          "         .named_steps['encoder']\n",
          "         .get_feature_names_out(CATEGORICAL_FEATURES)))\n", '\n',
          "importances = dt_best.named_steps['classifier'].feature_importances_\n",
          'feat_imp = pd.Series(importances, index=feature_names).sort_values(ascending=False)\n', '\n',
          'fig, ax = plt.subplots(figsize=(12, 8))\n',
          "feat_imp.head(15).plot(kind='barh', ax=ax, color='#e74c3c', edgecolor='black')\n",
          "ax.set_title('Top 15 Feature Importances — Decision Tree', fontsize=14, fontweight='bold')\n",
          'ax.invert_yaxis()\n',
          "plt.savefig('docs/eda_plots/feature_importance.png', dpi=150, bbox_inches='tight')\n",
          'plt.show()']),
]), 'notebooks/08_knn_and_tree.ipynb')

# ==================== 09_hyperparameter_tuning.ipynb ====================
save(make_nb([
    md(['# 09 — Hyperparameter Tuning\n',
        'GridSearchCV on Logistic Regression, RandomizedSearchCV on Decision Tree.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.linear_model import LogisticRegression\n',
          'from sklearn.tree import DecisionTreeClassifier\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n',
          'from sklearn.metrics import classification_report, f1_score\n',
          'from scipy.stats import randint\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import RANDOM_STATE']),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md('## 1. GridSearchCV on Logistic Regression'),
    code(["lr_pipeline = Pipeline(steps=[\n", "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))\n", '])\n', '\n',
          'param_grid = {\n', "    'classifier__C': [0.01, 0.1, 1, 10],\n",
          "    'classifier__solver': ['liblinear', 'lbfgs']\n", '}\n', '\n',
          "grid_lr = GridSearchCV(lr_pipeline, param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)\n",
          'grid_lr.fit(X_train, y_train)\n', '\n',
          'print(f"Best params: {grid_lr.best_params_}")\n',
          'print(f"Best CV F1: {grid_lr.best_score_:.4f}")\n', '\n',
          'y_pred_lr = grid_lr.predict(X_test)\n',
          'print(f"\\nTest F1 (class 1): {f1_score(y_test, y_pred_lr, pos_label=1):.4f}")\n',
          "print(classification_report(y_test, y_pred_lr, target_names=['No Default', 'Default']))"]),
    md(['## 2. RandomizedSearchCV on Decision Tree\n',
        'Randomized search is faster when the parameter space is large.\n',
        'Instead of trying all combinations, it samples n_iter random ones.']),
    code(["dt_pipeline = Pipeline(steps=[\n", "    ('preprocessor', build_preprocessor()),\n",
          "    ('classifier', DecisionTreeClassifier(random_state=RANDOM_STATE))\n", '])\n', '\n',
          'param_dist = {\n', "    'classifier__max_depth': [3, 5, 7, 10, None],\n",
          "    'classifier__min_samples_split': randint(2, 20),\n",
          "    'classifier__min_samples_leaf': randint(1, 10)\n", '}\n', '\n',
          'random_dt = RandomizedSearchCV(\n',
          "    dt_pipeline, param_dist, n_iter=20, cv=5, scoring='f1',\n",
          '    random_state=RANDOM_STATE, n_jobs=-1, verbose=1\n', ')\n',
          'random_dt.fit(X_train, y_train)\n', '\n',
          'print(f"Best params: {random_dt.best_params_}")\n',
          'print(f"Best CV F1: {random_dt.best_score_:.4f}")\n', '\n',
          'y_pred_dt = random_dt.predict(X_test)\n',
          'print(f"\\nTest F1 (class 1): {f1_score(y_test, y_pred_dt, pos_label=1):.4f}")\n',
          "print(classification_report(y_test, y_pred_dt, target_names=['No Default', 'Default']))"]),
    md(['## 3. Grid vs Randomized — When to Use Each\n',
        '| Method | When to Use |\n', '|--------|------------|\n',
        '| GridSearchCV | Small parameter space (< 20 combinations) |\n',
        '| RandomizedSearchCV | Large space; want good-enough params fast |\n',
        '| Both | Always use CV (never tune on test set!) |']),
]), 'notebooks/09_hyperparameter_tuning.ipynb')

# ==================== 10_model_comparison.ipynb ====================
save(make_nb([
    md(['# 10 — Model Comparison & Final Model Selection\n',
        'Train all 7 models, compare F1 scores, save results to CSV for Streamlit app.']),
    code(['import pandas as pd\n', 'import numpy as np\n',
          'from sklearn.dummy import DummyClassifier\n',
          'from sklearn.linear_model import LogisticRegression\n',
          'from sklearn.neighbors import KNeighborsClassifier\n',
          'from sklearn.tree import DecisionTreeClassifier\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.compose import ColumnTransformer\n',
          'from sklearn.impute import SimpleImputer\n',
          'from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder\n',
          'from sklearn.model_selection import GridSearchCV, RandomizedSearchCV\n',
          'from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score\n',
          'from imblearn.over_sampling import SMOTE\n',
          'from imblearn.pipeline import Pipeline as ImbPipeline\n',
          'from scipy.stats import randint\n',
          'import matplotlib.pyplot as plt\n',
          'from src.preprocess import build_preprocessor\n',
          'from src.config import NUMERICAL_FEATURES, CATEGORICAL_FEATURES, RANDOM_STATE, RESULTS_PATH\n',
          'import os']),
    code(["X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()\n",
          'print(f"Train: {X_train.shape}, Test: {X_test.shape}")']),
    md('## Train All 7 Models'),
    code([
        'results = []\n', '\n',
        'def evaluate(name, pipeline, X_tr, y_tr, X_te, y_te):\n',
        '    pipeline.fit(X_tr, y_tr)\n', '    y_pred = pipeline.predict(X_te)\n',
        '    scores = {\n', "        'Model': name,\n",
        "        'Accuracy': accuracy_score(y_te, y_pred),\n",
        "        'Precision (class 1)': precision_score(y_te, y_pred, pos_label=1, zero_division=0),\n",
        "        'Recall (class 1)': recall_score(y_te, y_pred, pos_label=1, zero_division=0),\n",
        "        'Test F1 (class 1)': f1_score(y_te, y_pred, pos_label=1, zero_division=0),\n",
        '    }\n', '    results.append(scores)\n',
        '    print(f"{name:30s} | F1={scores[\'Test F1 (class 1)\']:.4f}")\n',
        '    return pipeline\n', '\n',
        '# 1. Dummy Baseline\n',
        "evaluate('Dummy Baseline',\n",
        "    Pipeline([('preprocessor', build_preprocessor()),\n",
        "              ('classifier', DummyClassifier(strategy='most_frequent', random_state=RANDOM_STATE))]),\n",
        '    X_train, y_train, X_test, y_test)\n', '\n',
        '# 2. Logistic Regression\n',
        "evaluate('Logistic Regression',\n",
        "    Pipeline([('preprocessor', build_preprocessor()),\n",
        "              ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))]),\n",
        '    X_train, y_train, X_test, y_test)\n', '\n',
        '# 3. LR + class_weight\n',
        "evaluate('LR + class_weight',\n",
        "    Pipeline([('preprocessor', build_preprocessor()),\n",
        "              ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE, class_weight='balanced'))]),\n",
        '    X_train, y_train, X_test, y_test)\n', '\n',
        '# 4. LR + SMOTE\n',
        "evaluate('LR + SMOTE',\n",
        "    ImbPipeline([('preprocessor', build_preprocessor()),\n",
        "                 ('smote', SMOTE(random_state=RANDOM_STATE)),\n",
        "                 ('classifier', LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))]),\n",
        '    X_train, y_train, X_test, y_test)\n', '\n',
        '# 5. KNN (sampled)\n',
        'SAMPLE_SIZE = 30000\n', 'np.random.seed(RANDOM_STATE)\n',
        'sample_idx = np.random.choice(len(X_train), size=min(SAMPLE_SIZE, len(X_train)), replace=False)\n',
        'X_train_knn = X_train.iloc[sample_idx]\n',
        'y_train_knn = y_train[sample_idx]\n', '\n',
        'knn_num = Pipeline([("imputer", SimpleImputer(strategy="median")), ("scaler", MinMaxScaler())])\n',
        'knn_cat = Pipeline([("imputer", SimpleImputer(strategy="most_frequent")), ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False))])\n',
        'knn_pre = ColumnTransformer([("num", knn_num, NUMERICAL_FEATURES), ("cat", knn_cat, CATEGORICAL_FEATURES)])\n',
        "knn_pipe = Pipeline([('preprocessor', knn_pre), ('classifier', KNeighborsClassifier())])\n",
        "grid_knn = GridSearchCV(knn_pipe, {'classifier__n_neighbors': [3, 5, 7, 11, 15]}, cv=5, scoring='f1', n_jobs=-1)\n",
        'grid_knn.fit(X_train_knn, y_train_knn)\n',
        "evaluate(f'KNN (k={grid_knn.best_params_[\"classifier__n_neighbors\"]})',\n",
        '    grid_knn.best_estimator_, X_train_knn, y_train_knn, X_test, y_test)\n', '\n',
        '# 6. Decision Tree (GridSearch)\n',
        "dt_pipe = Pipeline([('preprocessor', build_preprocessor()),\n",
        "                     ('classifier', DecisionTreeClassifier(random_state=RANDOM_STATE))])\n",
        "grid_dt = GridSearchCV(dt_pipe, {'classifier__max_depth': [3, 5, 7, 10]}, cv=5, scoring='f1', n_jobs=-1)\n",
        'grid_dt.fit(X_train, y_train)\n',
        "evaluate(f'DT GridSearch (depth={grid_dt.best_params_[\"classifier__max_depth\"]})',\n",
        '    grid_dt.best_estimator_, X_train, y_train, X_test, y_test)\n', '\n',
        '# 7. Decision Tree (RandomizedSearch)\n',
        "random_dt = RandomizedSearchCV(dt_pipe, \n",
        "    {'classifier__max_depth': [3, 5, 7, 10, None], 'classifier__min_samples_split': randint(2, 20), 'classifier__min_samples_leaf': randint(1, 10)},\n",
        "    n_iter=20, cv=5, scoring='f1', random_state=RANDOM_STATE, n_jobs=-1)\n",
        'random_dt.fit(X_train, y_train)\n',
        "evaluate('DT RandomizedSearch',\n",
        '    random_dt.best_estimator_, X_train, y_train, X_test, y_test)'
    ]),
    md('## Results Table'),
    code(["results_df = pd.DataFrame(results).round(4)\n",
          "results_df = results_df.sort_values('Test F1 (class 1)', ascending=False)\n",
          'print(results_df.to_string(index=False))']),
    md('## Visualization'),
    code(['fig, ax = plt.subplots(figsize=(12, 6))\n',
          "colors = ['#e74c3c' if i == 0 else '#3498db' for i in range(len(results_df))]\n",
          "ax.barh(results_df['Model'], results_df['Test F1 (class 1)'], color=colors, edgecolor='black')\n",
          "ax.set_xlabel('F1 Score (class 1)')\n",
          "ax.set_title('Model Comparison — Test F1 on Default Class', fontsize=14, fontweight='bold')\n",
          'ax.invert_yaxis()\n', "ax.grid(True, axis='x', alpha=0.3)\n",
          "plt.savefig('docs/eda_plots/model_comparison.png', dpi=150, bbox_inches='tight')\n",
          'plt.show()']),
    md('## Save Results for Streamlit App'),
    code(["results_df.to_csv(RESULTS_PATH, index=False)\n",
          'print(f"Results saved to {RESULTS_PATH}")\n',
          'print("The Streamlit app will load this CSV for the model comparison tab.")']),
    md(['## Final Model Selection\n',
        'Select the model with highest Test F1 (class 1).\n',
        'Store the pipeline variable for pickling in the next notebook.']),
    code(["best_model_name = results_df.iloc[0]['Model']\n",
          "best_f1 = results_df.iloc[0]['Test F1 (class 1)']\n",
          'print(f"Best model: {best_model_name}")\n',
          'print(f"Test F1 (class 1): {best_f1:.4f}")\n', '\n',
          '# Store the best pipeline for Milestone 18\n',
          '# In practice, retrain the best model config on full train set\n',
          "final_pipeline = grid_dt.best_estimator_  # update this based on actual results\n",
          'print(f"\\nfinal_pipeline ready for pickling")']),
]), 'notebooks/10_model_comparison.ipynb')

# ==================== 11_save_and_load.ipynb ====================
save(make_nb([
    md(['# 11 — Save & Load Model with Pickle\n',
        'Serialize the complete pipeline and verify prediction integrity.']),
    code(['import pandas as pd\n', 'import numpy as np\n', 'import pickle\n', 'import os\n',
          'from src.config import MODEL_PATH, RANDOM_STATE\n',
          'from src.inference import load_model, predict']),
    code(["X_test = pd.read_csv('data/processed/X_test.csv')\n",
          "y_test = pd.read_csv('data/processed/y_test.csv').values.ravel()"]),
    md(['## 1. Why Pickle the ENTIRE Pipeline?\n',
        'The pipeline contains both the preprocessor and the model.\n',
        'If you pickle only the model, you lose the fitted scaler/encoder,\n',
        'and inference on raw data will fail or produce wrong results.']),
    md('## 2. Load Best Model from Previous Notebook'),
    code(['# Re-train the best model (or load from previous notebook)\n',
          'from sklearn.tree import DecisionTreeClassifier\n',
          'from sklearn.pipeline import Pipeline\n',
          'from sklearn.model_selection import GridSearchCV\n',
          'from src.preprocess import build_preprocessor\n', '\n',
          "X_train = pd.read_csv('data/processed/X_train.csv')\n",
          "y_train = pd.read_csv('data/processed/y_train.csv').values.ravel()\n", '\n',
          "dt_pipe = Pipeline([('preprocessor', build_preprocessor()),\n",
          "                     ('classifier', DecisionTreeClassifier(random_state=RANDOM_STATE))])\n",
          "grid_dt = GridSearchCV(dt_pipe, {'classifier__max_depth': [3, 5, 7, 10]}, cv=5, scoring='f1', n_jobs=-1)\n",
          'grid_dt.fit(X_train, y_train)\n',
          'final_pipeline = grid_dt.best_estimator_\n',
          'print(f"Best model: {final_pipeline}")']),
    md('## 3. Save to Pickle'),
    code(["os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)\n", '\n',
          "with open(MODEL_PATH, 'wb') as f:\n", '    pickle.dump(final_pipeline, f)\n', '\n',
          'file_size = os.path.getsize(MODEL_PATH) / 1024\n',
          'print(f"Model saved to {MODEL_PATH}")\n',
          'print(f"File size: {file_size:.1f} KB")']),
    md('## 4. Load and Verify'),
    code(['loaded_model = load_model(MODEL_PATH)\n', '\n',
          '# Compare predictions on 5 test rows\n',
          'sample = X_test.iloc[:5]\n',
          'preds_original = final_pipeline.predict(sample)\n',
          'preds_loaded = loaded_model.predict(sample)\n', '\n',
          'print(f"Original predictions: {preds_original}")\n',
          'print(f"Loaded predictions:   {preds_loaded}")\n', '\n',
          'assert np.array_equal(preds_original, preds_loaded), "PREDICTIONS DO NOT MATCH!"\n',
          'print("\\n✓ Predictions match. Pipeline integrity confirmed.")']),
    md('## 5. Test inference.predict() function'),
    code(['sample_row = X_test.iloc[[0]]\n',
          'result = predict(loaded_model, sample_row)\n',
          'print(f"Prediction: {result[\'prediction\']} (0=No Default, 1=Default)")\n',
          'print(f"Probability of default: {result[\'probability\']:.4f}")']),
]), 'notebooks/11_save_and_load.ipynb')

print('\n✅ All notebooks created successfully!')
